metadata:
- appName: 公用
  dataId: common.yml
  desc: 公用
  group: DEFAULT_GROUP
  type: yaml
- appName: 公共
  dataId: redis.yml
  desc: 公共
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: mysql.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-oauth-server.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-monitor.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-gateway-server.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-base-server.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-system-server.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-generator-server.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: rocketmq.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-ws-server.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-presence-server.yml
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-im-server.yml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: luohuo-ai-server.yml
  group: DEFAULT_GROUP
  type: yaml
