server:
  port: 18778
luohuo:
  thread:
    multiplier: 2  # 线程乘数
    min: 4         # 最小线程数
    retry:
      max-count: 3      # 最大重试次数
      delay-seconds: 3  # 多久时候开始重试
  # 微信扫码配置
  wx:
    mp:
      callback: https://468ov9ww8878.vicp.fun
      configs:
        - appId: wxb28a0fd6d1cae6ba                           # 第一个公众号的appid
          secret: 9c215f8d078422805218221144b9095b            # 公众号的appsecret
          token: nongyehong
          aesKey: 7iNecFLZ8nbtCaMntHYEruSHP1Mk8FmGvrkHwnJzwug # 接口配置里的EncodingAESKey值
  mysql: &db-mysql
    filters: stat,wall
    db-type: mysql   
    validation-query: SELECT 'x'  
    username: 'luohuo_im_01'
    password: 'NHZEjXj2tJxt1rfa'
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.1.37:13306/luohuo_im_01?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
springdoc:
  group-configs:
    - group: 'system'
      displayName: 'system'
      paths-to-match: '/**'
      packages-to-scan: com.luohuo.flex.system.controller

# mysql 通用配置
spring:
  mail:
    host: smtp.163.com            # 邮箱SMTP服务器
    port: 465                    # SSL端口
    username: nongyehong919@163.com    # 发件人邮箱
    password: YZ7ju32X6WWSbx2e           # 邮箱SMTP授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
    # properties:
    #   mail:
    #     smtp:
    #       auth: true
    #       starttls:
    #         enable: true
    #       ssl:
    #         enable: false
    #         protocols: TLSv1.2 # 加密协议
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    dynamic:
      enabled: false
    druid:
      enable: true
      # 从这里开始(druid)，中间的这段配置用于 luohuo.database.multiTenantType != DATASOURCE 时
      <<: *db-mysql
      initialSize: 10
      minIdle: 10
      maxActive: 200
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: false
      time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
      filter:
        wall:
          enabled: true
          config:
            strictSyntaxCheck: false
            commentAllow: true
            multiStatementAllow: true
            noneBaseStatementAllow: true
        slf4j:
          enabled: false   # 使用slf4j打印可执行日志时，改成true
          statement-executable-sql-log-enable: true

      # 从这里结束(druid)，中间的这段配置用于 luohuo.database.multiTenantType != DATASOURCE 时
      
      # 以下的2段配置，同时适用于所有模式
      web-stat-filter:  # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
        session-stat-enable: false
      stat-view-servlet:  #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
        enabled: true
        url-pattern: /druid/*   #根据配置中的url-pattern来访问内置监控页面，如果是上面的配置，内置监控页面的首页是/druid/index.html例如：http://127.0.0.1:9000/druid/index.html
        reset-enable: true    #允许清空统计数据
        login-username: ''
        login-password: ''
        allow: ''