server:
  port: 18762
  servlet:
    context-path: /${spring.application.name}   # 监控系统项目名

spring:
  security:
    user:
      name: luohuo
      password: luohuo
      roles: USER

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true
